amqp_port: 443
display_name: electrochemistry_testing_gep
engine:
  max_workers_per_node: 1
  provider:
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0
    type: LocalProvider
  type: GlobusComputeEngine