version: '3.9'

services:
  acl_mservice:
    build:
      context: ./instrument_mService
      dockerfile: Dockerfile
    container_name: instrumentcontrol
    #ports:
    #  - "5001:5001"
    networks:
      custom_net:
        ipv4_address: 192.168.100.10

  orchestrator_mservice:
    build:
      context: ./workflow_orchestrator_mService
      dockerfile: Dockerfile
    container_name: workfloworchestration
    environment:
      XXGLOBUS_TOKEN: 8Tqhvo9UHRavQFj8dIChravAxkZ78j
    #ports:
    #  - "5001:5001"
    networks:
      custom_net:
        ipv4_address: 192.168.100.20

  compute_mservice:
    build:
      context: ./compute_mService
      dockerfile: Dockerfile
    container_name: iv_inference_ep
    networks:
      custom_net:
        ipv4_address: 192.168.100.30

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
